from objfun import *
from data_construction import *
from Bilinear_Interpolation import *
import matplotlib.pyplot as plt

def main():
    #fig = plt.figure() 
    #ax3 = plt.axes(projection='3d')
    data_10=twoD_data(10)
    data_20=twoD_data(20)
    xx = np.arange(-2,2,0.05)
    yy = np.arange(-2,2,0.05)
    X, Y = np.meshgrid(xx, yy)
    m=len(yy)
    n=len(xx)
    Z10=np.zeros((m,n))
    Z20=np.zeros((m,n))
    Z_true=np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            #Z[i][j]=f(xx[j],yy[i])
            Z10[i][j]=Bilinear_Interpolation(xx[j],yy[i],data_10)
            Z20[i][j]=Bilinear_Interpolation(xx[j],yy[i],data_20)
            Z_true[i][j]=objfun4(xx[j],yy[i])
    fig=plt.figure()
    plt.title('bilinear',fontsize=9)
    fig.set_size_inches(9, 3)
    ax1=fig.add_subplot(131,projection='3d') 
    ax2=fig.add_subplot(132,projection='3d') 
    ax3=fig.add_subplot(133,projection='3d') 
    ax1.plot_surface(X,Y,Z10,cmap='rainbow')
    ax2.plot_surface(X,Y,Z20,cmap='rainbow')
    ax3.plot_surface(X,Y,Z_true,cmap='rainbow')
    ax1.set_title('n=10')
    ax2.set_title('n=20')
    ax3.set_title('objfun')
    plt.show()
def main2():
    data_10=twoD_data(10)
    data_20=twoD_data(20)
    xx = np.arange(-2,2,0.05)
    yy = np.arange(-2,2,0.05)
    X, Y = np.meshgrid(xx, yy)
    m=len(yy)
    n=len(xx)
    Z10=np.zeros((m,n))
    Z20=np.zeros((m,n))
    Z_true=np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            #Z[i][j]=f(xx[j],yy[i])
            Z10[i][j]=NN_Interpolation(xx[j],yy[i],data_10)
            Z20[i][j]=NN_Interpolation(xx[j],yy[i],data_20)
            Z_true[i][j]=objfun4(xx[j],yy[i])
    fig=plt.figure()
    plt.title('Nearest Neighbor',fontsize=9)
    fig.set_size_inches(9, 3)
    ax1=fig.add_subplot(131,projection='3d') 
    ax2=fig.add_subplot(132,projection='3d') 
    ax3=fig.add_subplot(133,projection='3d') 
    ax1.plot_surface(X,Y,Z10,cmap='rainbow')
    ax2.plot_surface(X,Y,Z20,cmap='rainbow')
    ax3.plot_surface(X,Y,Z_true,cmap='rainbow')
    ax1.set_title('n=10')
    ax2.set_title('n=20')
    ax3.set_title('objfun')
    plt.show()
if __name__ == '__main__':
    main()
    main2()